### ISSUE TITLE
Incomplete type( std::atomic )  is not allowed?

### ISSUE THREAD

**Issue by KnIfER** [jwezorek/vs_pdfium#2] opened 2020-10-20 13:09 UTC
![image](https://user-images.githubusercontent.com/11593903/96590423-f7ab1e00-1320-11eb-8938-c69b9b0d78b6.png)

**Comment by KnIfER** [comment] 2020-10-20 13:22
This problem occurs when using VS2019, just change to VS2017.

**Comment by jwezorek** [comment] 2020-10-24 15:21
Hmmm... I actually build under vs2019 all the time, but I do remember this error. I forget how I got around it...

Yes, I just verified that I can build in vs2019 without changes. What version number of Visual Studio 2019 are you using? I can build with Version 16.7.3.

**Comment by KnIfER** [comment] 2020-10-30 22:41
16.1.5

**Comment by tjenniges** [comment] 2021-03-06 17:35
I'm getting the exact errors with VS 2019 when building. Using VS 2017 isn't an option. 
jwezorek,  did you ever figure this out?

**Comment by tjenniges** [comment] 2021-03-06 20:53
FYI. It builds with 2019.  BUT make sure 2019 doesn't upgrade the target platform toolset from v141 the first time you open the solution. I'm curious why v142 (2019) will not work.

![image](https://user-images.githubusercontent.com/11098111/110220450-139ffe00-7e83-11eb-8bf2-fa9474d01ed0.png)

**Comment by jwezorek** [comment] 2021-03-09 16:58
Yes, I can confirm the problem is building toolset v142 or above.

**Comment by jwezorek** [comment] 2021-03-09 17:00
I wonder if just defining U_HAVE_STD_ATOMICS fixes the problem? I will check this...

**Comment by jwezorek** [comment] 2021-03-09 17:39
Actually U_HAVE_STD_ATOMICS is already defined. The problem is the line #63 in umutex.h. 

template <> struct U_COMMON_API std::atomic<int32_t>;

we want that to be ifdef'ed out, I think, but it will currently be defined. I think this is an error in the pdfium code, well icu code. With google's tools they only ever build with gcc, cygwin, etc. so the ifdef for platform equals windows means that environment, for building with VS we want the following to be undefined

#if U_PF_WINDOWS <= U_PLATFORM && U_PLATFORM <= U_PF_CYGWIN && !defined(U_IN_DOXYGEN)
  #if defined(__clang__) && __has_warning("-Winstantiation-after-specialization")
    // Suppress the warning that the explicit instantiation after explicit specialization has no effect.
    #pragma clang diagnostic ignored "-Winstantiation-after-specialization"
  #endif
template <> struct U_COMMON_API std::atomic<int32_t>;
#endif

Is there a preprocessor definition to test for building with Visual Studio? I could just wrap the "template <>..." line in an undef on that.

Actually i think this could be fixed by updating the ICU code to the latest. I updated pdfium recently but not third party libraries

**Closed as completed** 2021-03-09 18:27 UTC

**Comment by jwezorek** [comment] 2021-03-09 18:28
i just commented out that line in the ICU code, updated the platform toolset to v142, and am closing this ticket. I will file another ticket about updating the third party folder to current source code
